 
stages:
  - build

bookworm:
  image: amd64/debian:bookworm
  stage: build
  script:
    - apt-get update && apt-get -fuy install build-essential cmake libboost-all-dev nlohmann-json3-dev pkg-config libcurlpp-dev
    - cmake . && make

sid:
  image: amd64/debian:sid
  stage: build
  script:
    - apt-get update && apt-get -fuy install build-essential cmake libboost-all-dev nlohmann-json3-dev pkg-config libcurlpp-dev
    - cmake . && make

