image: amd64/debian:bookworm
 
stages:
  - build

bookworm:
  stage: build
  script:
    - apt-get update && apt-get -fuy install build-essential cmake libboost-all-dev nlohmann-json3-dev pkg-config
    - cmake . && make

